import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import { BmError, type ProjectConfig } from '@bm/shared';
import type { Ctx } from '../context';
import { docker, dockerCli, imageExists, networkExists } from './client';
import { ensureTraefik, TRAEFIK_PROJECT } from './traefik';
import { pgPing } from '../pg';
import { runtimeState } from '../state';
import { excludedPortRanges, inPortRanges, listeningPorts } from '../util/ports';
import { log } from '../util/logger';
import { onProjectConfigChanged } from '../services/projects';
import { audit } from '../services/audit';

/**
 * `postgres.mode: managed` (docs/decisions.md D30): the app runs one Postgres container per project, `bm-<project>-db`,
 * in the project network under the alias `postgres.internalHost`, with a named volume and a port on 127.0.0.1 only.
 * The container carries `bm.managed=postgres` and no `bm.project` label, so reconciliation never lists it as an orphan;
 * only deleting the project removes it.
 */
export const managedPgName = (projectId: string): string => `bm-${projectId}-db`;
export const managedPgVolume = (projectId: string): string => `bm-${projectId}-pgdata`;

// Below the Windows dynamic range 49152–65535, where Hyper-V / WSL reserve port blocks after a reboot (D62).
const PORT_FROM = 15432;
const PORT_TO = 15531;

export function managedPgCompose(cfg: ProjectConfig): string {
  const name = managedPgName(cfg.id);
  const pg = cfg.postgres;
  const net = cfg.runtime.network;
  const doc = {
    name,
    services: {
      db: {
        image: pg.image,
        container_name: name,
        environment: { POSTGRES_USER: pg.user, POSTGRES_PASSWORD: pg.password, POSTGRES_DB: 'postgres' },
        volumes: [{ type: 'volume', source: 'pgdata', target: '/var/lib/postgresql/data' }],
        ports: [`127.0.0.1:${pg.port}:5432`],
        networks: { [net]: { aliases: [pg.internalHost] } },
        labels: { 'bm.managed': 'postgres', 'bm.pg-project': cfg.id },
        healthcheck: { test: ['CMD-SHELL', `pg_isready -U ${pg.user} -d postgres`], interval: '5s', timeout: '5s', retries: 10 },
        shm_size: '256mb',
        restart: 'unless-stopped',
      },
    },
    volumes: { pgdata: { name: managedPgVolume(cfg.id) } },
    networks: { [net]: { external: true, name: net } },
  };
  // `$` would be interpolated by compose: escape it (passwords are generated without it, but a hand-edited one may have it).
  const text = YAML.stringify(doc, { lineWidth: 0 }).replace(/\$/g, '$$$$');
  return `# Generated by Odoo Branch Manager: Postgres of project ${cfg.id} (postgres.mode: managed).\n${text}`;
}

const composeFile = (ctx: Ctx, projectId: string): string => path.join(ctx.dataDir, 'postgres', projectId, 'compose.yml');

/** A free host port for a new managed Postgres: not listening, not reserved by Windows, not taken by another project. */
export async function allocatePgPort(ctx: Ctx): Promise<number> {
  const busy = await listeningPorts().catch(() => new Set<number>());
  const reserved = await excludedPortRanges().catch(() => []);
  const taken = new Set(ctx.store.list().map((e) => e.config?.postgres.port));
  for (let p = PORT_FROM; p <= PORT_TO; p++) if (!busy.has(p) && !taken.has(p) && !inPortRanges(p, reserved)) return p;
  throw new BmError('NO_PORT', `Нет свободного порта для Postgres в диапазоне ${PORT_FROM}–${PORT_TO}`);
}

/** Creates the project network (when missing), labelled as the app's own. */
export async function ensureNetwork(cfg: ProjectConfig, say: (l: string) => void = () => {}): Promise<boolean> {
  if (await networkExists(cfg.runtime.network)) return false;
  say(`docker network create ${cfg.runtime.network}`);
  const r = await dockerCli(['network', 'create', '--label', 'bm.managed=network', '--label', `bm.pg-project=${cfg.id}`, cfg.runtime.network]);
  if (r.exitCode !== 0 && !(await networkExists(cfg.runtime.network))) throw new BmError('DOCKER', `Не удалось создать сеть ${cfg.runtime.network}: ${r.stderr.trim()}`);
  return true;
}

/** `docker pull` with the progress lines of each layer thinned out (the first image download may take minutes). */
export async function pullImage(image: string, say: (l: string) => void, signal?: AbortSignal): Promise<void> {
  if (await imageExists(image)) return;
  say(`docker pull ${image} (первая загрузка может занять несколько минут)`);
  let last = 0;
  const r = await dockerCli(['pull', image], {
    timeoutMs: 1_800_000,
    signal,
    onLine: (l) => {
      if (/Downloading|Extracting|Waiting|Verifying/.test(l) && Date.now() - last < 5000) return;
      last = Date.now();
      say(l);
    },
  });
  if (r.exitCode !== 0) throw new BmError('DOCKER_PULL', `Не удалось скачать образ ${image}: ${(r.stderr || r.stdout).trim().split('\n').pop()}`);
}

const inFlight = new Map<string, Promise<void>>();

/** Idempotent: network, image, container up, Postgres accepting connections, Traefik attached to the network. */
export function ensureManagedPostgres(ctx: Ctx, cfg: ProjectConfig, say: (l: string) => void = () => {}): Promise<void> {
  if (cfg.postgres.mode !== 'managed') return Promise.resolve();
  let p = inFlight.get(cfg.id);
  if (!p) {
    p = doEnsure(ctx, cfg, say).finally(() => inFlight.delete(cfg.id));
    inFlight.set(cfg.id, p);
  }
  return p;
}

/**
 * The configured host port fell into a range Windows reserved (D62): the container runs, but Docker could not publish
 * the port, and Core, which works with databases from the host, loses Postgres. Branch containers connect by the
 * network alias and do not use this port, so the app moves it to a free one and saves it into the project settings.
 */
async function movePgPort(ctx: Ctx, cfg: ProjectConfig, say: (l: string) => void): Promise<ProjectConfig> {
  const e = ctx.store.get(cfg.id);
  const saved = e?.config?.postgres;
  // A config that is not the saved one (migration to managed checks its target port itself) is not rewritten.
  if (!e || saved?.mode !== 'managed' || saved.port !== cfg.postgres.port) {
    throw new BmError('PORT_RESERVED', `Порт ${cfg.postgres.port} для Postgres зарезервирован Windows (netsh interface ipv4 show excludedportrange protocol=tcp). Укажите другой postgres.port в настройках проекта.`);
  }
  const port = await allocatePgPort(ctx);
  say(`Порт ${cfg.postgres.port} зарезервирован Windows (Hyper-V / WSL), Docker не может его опубликовать: Postgres переезжает на 127.0.0.1:${port}`);
  const doc = YAML.parseDocument(e.text);
  doc.setIn(['postgres', 'port'], port);
  const next = ctx.store.putProject(doc.toString(), { expectId: cfg.id });
  onProjectConfigChanged(ctx, e.config, next);
  audit(ctx, { projectId: cfg.id, action: 'postgres.port', target: managedPgName(cfg.id), params: { from: cfg.postgres.port, to: port }, result: 'reserved by Windows' });
  log().warn({ project: cfg.id, from: cfg.postgres.port, to: port }, 'managed postgres port reserved by Windows, moved');
  return next;
}

async function doEnsure(ctx: Ctx, cfg: ProjectConfig, say: (l: string) => void): Promise<void> {
  if (!cfg.postgres.password) throw new BmError('PG_NO_PASSWORD', 'У managed Postgres нет пароля (postgres.password в настройках проекта).');
  if (!runtimeState.docker.ok) throw new BmError('DOCKER_DOWN', 'Docker недоступен: запустите Docker Desktop');
  const reserved = await excludedPortRanges().catch(() => []);
  if (inPortRanges(cfg.postgres.port, reserved)) cfg = await movePgPort(ctx, cfg, say);
  const pg = cfg.postgres;
  const name = managedPgName(cfg.id);
  const created = await ensureNetwork(cfg, say);
  const existing = await docker.getContainer(name).inspect().catch(() => null);
  const bound = existing?.HostConfig.PortBindings?.['5432/tcp']?.[0]?.HostPort;
  // Configured is not enough: Docker Desktop starts the container even when it could not publish the port.
  const published = !!existing?.NetworkSettings.Ports?.['5432/tcp']?.some((b) => b.HostPort === String(pg.port));
  const upToDate = existing?.State.Running && bound === String(pg.port) && published && existing.Config.Image === pg.image;
  if (!upToDate) {
    if (bound !== String(pg.port)) {
      const busy = await listeningPorts().catch(() => new Set<number>());
      if (busy.has(pg.port)) throw new BmError('PORT_BUSY', `Порт ${pg.port} для Postgres занят другим процессом. Укажите другой postgres.port в настройках проекта.`);
    }
    await pullImage(pg.image, say);
    const file = composeFile(ctx, cfg.id);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, managedPgCompose(cfg), 'utf8');
    say(`docker compose -p ${name} up -d`);
    // Same compose config with an unpublished port: compose would keep the container as it is.
    const recreate = existing?.State.Running && bound === String(pg.port) && !published ? ['--force-recreate'] : [];
    const r = await dockerCli(['compose', '-p', name, '-f', file, 'up', '-d', '--remove-orphans', ...recreate], { timeoutMs: 180_000, onLine: say });
    if (r.exitCode !== 0) throw new BmError('DOCKER', `Postgres не запустился: ${(r.stderr || r.stdout).trim()}`);
  }
  // Ready = accepts connections from the host (the first start initialises the data directory).
  const deadline = Date.now() + 90_000;
  for (;;) {
    try {
      const v = await pgPing(pg);
      runtimeState.postgres.set(cfg.id, { ok: true, text: `${pg.host}:${pg.port}, PostgreSQL ${v} (managed)` });
      break;
    } catch (err) {
      if (Date.now() > deadline) throw new BmError('PG_CONNECT', `Postgres ${name} не отвечает: ${(err as Error).message}`);
      await new Promise((res) => setTimeout(res, 1500));
    }
  }
  if (created || !upToDate) await ensureTraefik(ctx);
  if (!upToDate) say(`Postgres ${name} работает на 127.0.0.1:${pg.port}`);
}

export interface ExternalPgContainer {
  id: string;
  name: string;
  image: string;
  running: boolean;
}

/**
 * The container behind an external Postgres (e.g. `db` of the user's own compose project): in the project network
 * under the alias `postgres.internalHost`, or publishing `postgres.port`. Branch containers are never candidates.
 */
export async function externalPgContainer(cfg: ProjectConfig): Promise<ExternalPgContainer | null> {
  const pg = cfg.postgres;
  const net = cfg.runtime.network;
  const list = await docker.listContainers({ all: true }).catch(() => []);
  const names = (c: (typeof list)[number]) => c.Names.map((n) => n.replace(/^\//, ''));
  const candidates = list.filter((c) => !c.Labels['bm.project'] && (c.NetworkSettings?.Networks?.[net] || names(c).some((n) => pg.protectedContainers.includes(n))));
  for (const c of candidates) {
    const info = await docker.getContainer(c.Id).inspect().catch(() => null);
    if (!info) continue;
    const ep = info.NetworkSettings.Networks?.[net] as { Aliases?: string[] | null; DNSNames?: string[] | null } | undefined;
    const alias = [...(ep?.Aliases ?? []), ...(ep?.DNSNames ?? [])].includes(pg.internalHost);
    const port = info.HostConfig.PortBindings?.['5432/tcp']?.some((b: { HostPort?: string }) => b.HostPort === String(pg.port));
    if (alias || port) return { id: info.Id, name: info.Name.replace(/^\//, ''), image: info.Config.Image, running: info.State.Running };
  }
  return null;
}

/**
 * `postgres.mode: external`: a stopped Postgres container of the user's stack (found by `externalPgContainer`) is
 * started before a branch needs it — otherwise Odoo loops on «could not translate host name "db"».
 */
async function ensureExternalPostgres(cfg: ProjectConfig, say: (l: string) => void): Promise<void> {
  const pg = cfg.postgres;
  let first: Error;
  try {
    await pgPing(pg);
    return;
  } catch (err) {
    first = err as Error;
  }
  if (!runtimeState.docker.ok) throw first;
  const c = await externalPgContainer(cfg);
  if (!c) throw first;
  if (!c.running) {
    say(`Postgres ${pg.host}:${pg.port} недоступен: запускаю контейнер ${c.name} (docker start)`);
    try {
      await docker.getContainer(c.id).start();
    } catch (err) {
      throw new BmError('PG_START', `Не удалось запустить контейнер Postgres ${c.name}: ${(err as Error).message}`);
    }
  }
  const deadline = Date.now() + 90_000;
  for (;;) {
    try {
      const v = await pgPing(pg);
      runtimeState.postgres.set(cfg.id, { ok: true, text: `${pg.host}:${pg.port}, PostgreSQL ${v}` });
      say(`Postgres ${c.name} работает`);
      return;
    } catch (err) {
      if (Date.now() > deadline) throw new BmError('PG_CONNECT', `Postgres ${c.name} не отвечает: ${(err as Error).message}`);
      await new Promise((res) => setTimeout(res, 1500));
    }
  }
}

/** Postgres of the project is up before a branch container starts: the app's own (managed) or the user's (external). */
export function ensurePostgres(ctx: Ctx, cfg: ProjectConfig, say: (l: string) => void = () => {}): Promise<void> {
  return cfg.postgres.mode === 'managed' ? ensureManagedPostgres(ctx, cfg, say) : ensureExternalPostgres(cfg, say);
}

/** Project deletion: container, data volume, compose folder and the project network (Traefik is detached first). */
export async function removeManagedPostgres(ctx: Ctx, cfg: ProjectConfig, say: (l: string) => void): Promise<void> {
  if (cfg.postgres.mode !== 'managed') return;
  const name = managedPgName(cfg.id);
  const file = composeFile(ctx, cfg.id);
  say(`docker compose -p ${name} down -v`);
  const r = fs.existsSync(file)
    ? await dockerCli(['compose', '-p', name, '-f', file, 'down', '-v', '--remove-orphans'], { timeoutMs: 180_000 })
    : { exitCode: 1, stdout: '', stderr: '' };
  if (r.exitCode !== 0) {
    const c = await docker.getContainer(name).inspect().catch(() => null);
    if (c && c.Config.Labels?.['bm.managed'] === 'postgres' && c.Config.Labels['bm.pg-project'] === cfg.id) {
      await docker.getContainer(name).remove({ force: true, v: true }).catch((e) => say(`контейнер: ${(e as Error).message}`));
    }
    await docker.getVolume(managedPgVolume(cfg.id)).remove().catch(() => {});
  }
  fs.rmSync(path.dirname(file), { recursive: true, force: true });
  const net = await docker.getNetwork(cfg.runtime.network).inspect().catch(() => null);
  if (net && net.Labels?.['bm.managed'] === 'network' && net.Labels['bm.pg-project'] === cfg.id) {
    await docker.getNetwork(cfg.runtime.network).disconnect({ Container: TRAEFIK_PROJECT, Force: true }).catch(() => {});
    say(`docker network rm ${cfg.runtime.network}`);
    await docker.getNetwork(cfg.runtime.network).remove().catch((e) => say(`сеть: ${(e as Error).message}`));
  }
  runtimeState.postgres.delete(cfg.id);
  log().info({ project: cfg.id }, 'managed postgres removed');
}
