import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import type { Ctx } from '../context';
import { docker, dockerCli, imageExists, networkExists } from './client';
import { runtimeState } from '../state';
import { listeningPorts } from '../util/ports';
import { bus } from '../events';
import { log } from '../util/logger';
import { t } from '../i18n';

export const TRAEFIK_PROJECT = 'bm-traefik';
const CONTAINER = 'bm-traefik';
/** Bumped when the generated compose changes in a way an existing container must pick up (it is then recreated). */
const CONFIG_VERSION = '3';
/** File-provider folder inside the container, on tmpfs: one-off routes of «Войти как» (D66) never outlive Traefik. */
const DYNAMIC_DIR = '/dynamic';

/** Networks Traefik must join: the network of every configured project that exists in Docker. */
async function projectNetworks(ctx: Ctx): Promise<string[]> {
  const nets = new Set<string>();
  for (const e of ctx.store.list()) if (e.config) nets.add(e.config.runtime.network);
  const out: string[] = [];
  for (const n of [...nets].sort()) if (await networkExists(n)) out.push(n);
  return out;
}

export function traefikCompose(image: string, port: number, networks: string[]): string {
  const doc = {
    name: TRAEFIK_PROJECT,
    services: {
      traefik: {
        image,
        container_name: CONTAINER,
        command: [
          '--providers.docker=true',
          '--providers.docker.exposedbydefault=false',
          // Inside the container: inotify of a Windows bind mount does not reach Docker's VM, the watcher would miss files.
          `--providers.file.directory=${DYNAMIC_DIR}`,
          '--providers.file.watch=true',
          '--entrypoints.web.address=:80',
          '--accesslog=true',
          '--accesslog.format=json',
          '--log.level=WARN',
          '--api.dashboard=false',
          '--ping=false',
        ],
        // Loopback only: builds are reachable from this machine and nowhere else (spec 11).
        ports: [`127.0.0.1:${port}:80`],
        volumes: [{ type: 'bind', source: '/var/run/docker.sock', target: '/var/run/docker.sock', read_only: true }],
        tmpfs: [DYNAMIC_DIR],
        networks: networks.length ? networks : undefined,
        labels: { 'bm.managed': 'traefik', 'bm.traefik-config': CONFIG_VERSION },
        // The access log (stdout) is read for build activity (D45): bounded, it does not grow forever.
        logging: { driver: 'json-file', options: { 'max-size': '20m', 'max-file': '3' } },
        restart: 'unless-stopped',
      },
    },
    networks: networks.length ? Object.fromEntries(networks.map((n) => [n, { external: true, name: n }])) : undefined,
  };
  return `# Generated by Odoo Branch Manager: shared Traefik for all projects.\n${YAML.stringify(doc, { lineWidth: 0 })}`;
}

/**
 * Writes a dynamic config file into the running Traefik (`docker exec`; written aside and renamed, so the watcher
 * never reads half a file). `name` is a plain `*.yml` file name.
 */
export async function writeTraefikDynamic(name: string, yaml: string): Promise<void> {
  const script = `cat > "${DYNAMIC_DIR}/.$1.tmp" && mv "${DYNAMIC_DIR}/.$1.tmp" "${DYNAMIC_DIR}/$1"`;
  const r = await dockerCli(['exec', '-i', CONTAINER, 'sh', '-c', script, 'sh', name], { input: yaml, timeoutMs: 30_000 });
  if (r.exitCode !== 0) throw new Error(r.stderr.trim() || r.stdout.trim() || t('traefik.execFailed', { container: CONTAINER, code: r.exitCode }));
}

/** Removes dynamic config files: one by name, or those matching `pattern` older than `minutes`. Errors are ignored. */
export async function removeTraefikDynamic(o: { name: string } | { pattern: string; minutes: number }): Promise<void> {
  const args =
    'name' in o
      ? ['rm', '-f', `${DYNAMIC_DIR}/${o.name}`]
      : ['find', DYNAMIC_DIR, '-maxdepth', '1', '-name', o.pattern, '-mmin', `+${o.minutes}`, '-delete'];
  await dockerCli(['exec', CONTAINER, ...args], { timeoutMs: 30_000 }).catch(() => undefined);
}

let ensuring: Promise<void> | null = null;

/**
 * Makes sure the shared Traefik runs on proxyPort and is attached to all project networks (spec 3).
 * Pulls the image once if missing (the only image download the app triggers).
 */
export function ensureTraefik(ctx: Ctx): Promise<void> {
  ensuring ??= doEnsure(ctx).finally(() => {
    ensuring = null;
  });
  return ensuring;
}

async function doEnsure(ctx: Ctx): Promise<void> {
  const app = ctx.store.app;
  const port = app.proxyPort;
  const image = app.traefik.image;
  try {
    const nets = await projectNetworks(ctx);
    const existing = await docker
      .getContainer(CONTAINER)
      .inspect()
      .catch(() => null);
    const bound = existing?.HostConfig.PortBindings?.['80/tcp']?.[0]?.HostPort;
    const attached = Object.keys(existing?.NetworkSettings.Networks ?? {});
    const upToDate =
      existing?.State.Running &&
      bound === String(port) &&
      existing.Config.Image === image &&
      existing.Config.Labels?.['bm.traefik-config'] === CONFIG_VERSION &&
      nets.every((n) => attached.includes(n));
    if (!upToDate) {
      if (!existing?.State.Running || bound !== String(port)) {
        const busy = await listeningPorts();
        if (busy.has(port) && bound !== String(port)) {
          throw new Error(t('traefik.portBusy', { port }));
        }
      }
      if (!(await imageExists(image))) {
        log().info({ image }, 'pulling traefik image');
        const r = await dockerCli(['pull', image], { timeoutMs: 600_000 });
        if (r.exitCode !== 0) throw new Error(t('traefik.pullFailed', { image, error: r.stderr.trim() }));
      }
      const dir = path.join(ctx.dataDir, 'traefik');
      fs.mkdirSync(dir, { recursive: true });
      const file = path.join(dir, 'compose.yml');
      fs.writeFileSync(file, traefikCompose(image, port, nets), 'utf8');
      const r = await dockerCli(['compose', '-p', TRAEFIK_PROJECT, '-f', file, 'up', '-d', '--remove-orphans'], { timeoutMs: 180_000 });
      if (r.exitCode !== 0) throw new Error(r.stderr.trim() || r.stdout.trim());
    }
    ctx.proxyPort = port;
    runtimeState.traefik = { ok: true, port, error: null };
  } catch (err) {
    runtimeState.traefik = { ok: false, port: null, error: t('traefik.notRunning', { error: (err as Error).message }) };
    log().warn({ err }, 'traefik ensure failed');
  }
  bus.emit({ type: 'system.changed' });
}
