import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import type { Ctx } from '../context';
import { docker, dockerCli, imageExists, networkExists } from './client';
import { runtimeState } from '../state';
import { listeningPorts } from '../util/ports';
import { bus } from '../events';
import { log } from '../util/logger';

export const TRAEFIK_PROJECT = 'bm-traefik';
const CONTAINER = 'bm-traefik';

/** Networks Traefik must join: the network of every configured project that exists in Docker. */
async function projectNetworks(ctx: Ctx): Promise<string[]> {
  const nets = new Set<string>();
  for (const e of ctx.store.list()) if (e.config) nets.add(e.config.runtime.network);
  const out: string[] = [];
  for (const n of [...nets].sort()) if (await networkExists(n)) out.push(n);
  return out;
}

export function traefikCompose(image: string, port: number, networks: string[]): string {
  const doc = {
    name: TRAEFIK_PROJECT,
    services: {
      traefik: {
        image,
        container_name: CONTAINER,
        command: [
          '--providers.docker=true',
          '--providers.docker.exposedbydefault=false',
          '--entrypoints.web.address=:80',
          '--accesslog=true',
          '--accesslog.format=json',
          '--log.level=WARN',
          '--api.dashboard=false',
          '--ping=false',
        ],
        // Loopback only: builds are reachable from this machine and nowhere else (spec 11).
        ports: [`127.0.0.1:${port}:80`],
        volumes: [{ type: 'bind', source: '/var/run/docker.sock', target: '/var/run/docker.sock', read_only: true }],
        networks: networks.length ? networks : undefined,
        labels: { 'bm.managed': 'traefik' },
        restart: 'unless-stopped',
      },
    },
    networks: networks.length ? Object.fromEntries(networks.map((n) => [n, { external: true, name: n }])) : undefined,
  };
  return `# Generated by Odoo Branch Manager: shared Traefik for all projects.\n${YAML.stringify(doc, { lineWidth: 0 })}`;
}

let ensuring: Promise<void> | null = null;

/**
 * Makes sure the shared Traefik runs on proxyPort and is attached to all project networks (spec 3).
 * Pulls the image once if missing (the only image download the app triggers).
 */
export function ensureTraefik(ctx: Ctx): Promise<void> {
  ensuring ??= doEnsure(ctx).finally(() => {
    ensuring = null;
  });
  return ensuring;
}

async function doEnsure(ctx: Ctx): Promise<void> {
  const app = ctx.store.app;
  const port = app.proxyPort;
  const image = app.traefik.image;
  try {
    const nets = await projectNetworks(ctx);
    const existing = await docker
      .getContainer(CONTAINER)
      .inspect()
      .catch(() => null);
    const bound = existing?.HostConfig.PortBindings?.['80/tcp']?.[0]?.HostPort;
    const attached = Object.keys(existing?.NetworkSettings.Networks ?? {});
    const upToDate =
      existing?.State.Running && bound === String(port) && existing.Config.Image === image && nets.every((n) => attached.includes(n));
    if (!upToDate) {
      if (!existing?.State.Running || bound !== String(port)) {
        const busy = await listeningPorts();
        if (busy.has(port) && bound !== String(port)) {
          throw new Error(`порт ${port} занят другим процессом. Укажите свободный порт в Settings → Приложение → Порт Traefik (например 8080).`);
        }
      }
      if (!(await imageExists(image))) {
        log().info({ image }, 'pulling traefik image');
        const r = await dockerCli(['pull', image], { timeoutMs: 600_000 });
        if (r.exitCode !== 0) throw new Error(`не удалось скачать образ ${image}: ${r.stderr.trim()}`);
      }
      const dir = path.join(ctx.dataDir, 'traefik');
      fs.mkdirSync(dir, { recursive: true });
      const file = path.join(dir, 'compose.yml');
      fs.writeFileSync(file, traefikCompose(image, port, nets), 'utf8');
      const r = await dockerCli(['compose', '-p', TRAEFIK_PROJECT, '-f', file, 'up', '-d', '--remove-orphans'], { timeoutMs: 180_000 });
      if (r.exitCode !== 0) throw new Error(r.stderr.trim() || r.stdout.trim());
    }
    ctx.proxyPort = port;
    runtimeState.traefik = { ok: true, port, error: null };
  } catch (err) {
    runtimeState.traefik = { ok: false, port: null, error: `Traefik не запущен: ${(err as Error).message}` };
    log().warn({ err }, 'traefik ensure failed');
  }
  bus.emit({ type: 'system.changed' });
}
