import crypto from 'node:crypto';
import type { ProjectConfig } from '@bm/shared';
import { serverBaseArgs } from '../builds/odoo-cli';
import { renderTemplate } from '../config/templates';
import { buildUrl } from '../docker/compose';
import { managedPgName } from '../docker/postgres';

/**
 * Skill for Claude Code / Cursor (D52): how an assistant finds a branch build, updates modules, runs tests and what it
 * leaves to the app. Generated from the project settings; `.claude/skills/<name>/SKILL.md` is read by both tools.
 * The text follows the app's behaviour: change it together with builds, labels and the Tools tab.
 */
export interface SkillInput {
  cfg: ProjectConfig;
  appVersion: string;
  /** Traefik port in use. */
  proxyPort: number;
  logsDir: string;
  configDir: string;
  /** Production, `repo.protectedBranches` and branches with the protected setting, known at generation time. */
  protectedBranches: string[];
  /** GitHub repository of the app (`updates.repository`), for issues. */
  appRepository: string;
  /** Launchers of the app's command line `bm` (D53); null — the skill only describes docker commands. */
  cli: { cmd: string | null; sh: string } | null;
  /** Windows host: Git Bash and PowerShell notes; otherwise (macOS, D67) plain zsh / bash. */
  windows: boolean;
}

export const skillName = (projectId: string): string => `branch-manager-${projectId}`;

const MARKER_RE = /^<!-- generated by Odoo Branch Manager (\S+); sha256:([0-9a-f]{16}) -->\s*$/m;

/** Hash of the skill text without the marker; line endings and trailing blanks do not count (git autocrlf). */
export function skillHash(body: string): string {
  const norm = body.replace(/\r\n/g, '\n').replace(/\s+$/, '');
  return crypto.createHash('sha256').update(norm).digest('hex').slice(0, 16);
}

/** Version and hash from the marker line, and whether the text before it still has that hash. */
export function parseSkill(text: string): { version: string; hash: string; modified: boolean } | null {
  const m = MARKER_RE.exec(text);
  if (!m) return null;
  const body = text.slice(0, m.index);
  return { version: m[1]!, hash: m[2]!, modified: skillHash(body) !== m[2] };
}

const code = (s: string): string => `\`${s}\``;
const list = (xs: string[]): string => xs.map(code).join(', ');

/** Example of a template for the Production branch; templates with variables it cannot know stay as they are. */
function example(tpl: string, cfg: ProjectConfig): string | null {
  const slug = cfg.production.slug;
  try {
    return renderTemplate(tpl, { project: cfg.id, branch: cfg.production.branch, slug, slug_: slug.replace(/-/g, '_'), stage: 'production', build: 1 });
  } catch {
    return null;
  }
}

export function renderSkill(i: SkillInput): string {
  const { cfg } = i;
  const id = cfg.id;
  const repo = cfg.repo.github ? `github.com/${cfg.repo.github}` : (cfg.repo.url ?? cfg.repo.path ?? '');
  const hostTpl = cfg.naming.host;
  const urlTpl = buildUrl(hostTpl, i.proxyPort);
  const prodHost = example(hostTpl, cfg);
  const prodDb = example(cfg.naming.db, cfg);
  const pg = cfg.postgres;
  const managed = pg.mode === 'managed';
  const pgName = managedPgName(id);
  const dbgPort = cfg.runtime.debug.containerPort;
  const hasDebug = cfg.runtime.command.some((a) => a === 'debugpy' || a.includes('debugpy'));
  // Options of builds made before the bm.odoo.args label: {addonsPath} is dropped here and taken from the container.
  const staticArgs = serverBaseArgs(cfg, { repoMount: cfg.runtime.repoMount }).join(' ');
  const usesAddonsPath = cfg.runtime.command.some((a) => a.includes('{addonsPath}'));
  const tagsTpl = cfg.stages.development?.tests?.tags?.trim() || '/{module}';
  const tags = tagsTpl.includes('{module}') ? tagsTpl.replaceAll('{module}', '<модуль>') : tagsTpl;
  const worktrees = `${cfg.repo.worktreesDir}/${id}/<slug>`;
  const local = cfg.repo.localFolder;
  const fetchText = cfg.repo.fetchIntervalMin > 0 ? `раз в ${cfg.repo.fetchIntervalMin} мин (или кнопкой «Обновить»)` : 'кнопкой «Обновить»';
  // With runtime.composeTemplate a build has extra services (D72): only its odoo container is the build.
  const filter = `--filter label=bm.project=${id} --filter label=com.docker.compose.oneoff=False${cfg.runtime.composeTemplate ? ' --filter label=com.docker.compose.service=odoo' : ''}`;
  const protectedOthers = [...new Set(i.protectedBranches)].filter((b) => b !== cfg.production.branch);
  // The app's own Postgres is listed separately (psql is allowed there).
  const protectedContainers = pg.protectedContainers.filter((c) => c !== pgName);
  const devDb = cfg.stages.development?.database ?? 'fresh';
  const prodUrl = prodHost ? buildUrl(prodHost, i.proxyPort) : null;
  // The user's own Odoo stack and databases: assistants reach for them (or for Production) instead of the branch build.
  const notBuilds = [...protectedContainers.map((c) => `контейнер ${code(c)}`), ...pg.protectedDbs.filter((d) => !/^(postgres|template[01])$/.test(d)).map((d) => `база ${code(d)}`)];

  const pgRow = managed
    ? `контейнер ${code(pgName)} (приложения), ${code(`${pg.host}:${pg.port}`)} на хосте, пользователь ${code(pg.user)}`
    : `внешний ${code(`${pg.host}:${pg.port}`)}, в сети ${code(cfg.runtime.network)} — ${code(pg.internalHost)}, пользователь ${code(pg.user)}`;
  const psql = managed
    ? ['```bash', `docker exec -it ${pgName} psql -U ${pg.user} -d $DB`, '```']
    : [
        `Postgres внешний: пароля у ассистента нет. Попроси пользователя открыть psql кнопкой в приложении (вкладка ветки`,
        `Shell → psql) или выполни запрос через ${code('odoo shell')} ниже.`,
      ];

  const lines: string[] = [
    '---',
    `name: ${skillName(id)}`,
    'description: >-',
    `  Локальные сборки веток проекта «${cfg.name}» в Odoo Branch Manager (локальный odoo.sh): найти сборку ветки,`,
    '  её URL, базу и порт debugpy; обновить модули (-u / -i) и запустить тесты в Development-сборке; логи, psql,',
    '  odoo shell; что можно делать только через приложение. Используй, когда нужно проверить изменения модулей Odoo',
    '  в сборке ветки или разобраться с её ошибкой. Работай в сборке своей ветки, а не в Production.',
    '---',
    '',
    `# ${cfg.name} — сборки веток в Odoo Branch Manager`,
    '',
    `> Файл создан приложением Odoo Branch Manager ${i.appVersion} по настройкам проекта ${code(id)}. Руками не правь:`,
    '> приложение обновляет его кнопкой в Settings проекта → «Ассистенты».',
    '',
    `Каждая ветка ${repo ? code(repo) : 'репозитория'} собирается отдельно: свой контейнер Odoo, своя база, свой код.`,
    'Сборками управляет пользователь в приложении; ассистенту доступны команды ниже.',
    '',
    '## Какая сборка твоя',
    '',
    'Проверяй, отлаживай, смотри логи и данные в сборке **той ветки, над которой работаешь**, — не в Production:',
    '',
    `1. Ветка — та, что назвал пользователь, иначе ${code('git branch --show-current')} в папке кода${local ? ` (${code(local)})` : ''}.`,
    `2. Её сборка — ${i.cli ? `${code('bm status')} или ` : ''}label ${code('bm.branch.name=<ветка>')} (раздел «Найти сборку»). База — только label`,
    `   ${code('bm.db')} этой сборки, адрес — ${code('bm.url')}.`,
    `3. Production ${code(cfg.production.branch)}${prodUrl ? ` (${code(prodUrl)})` : ''} — только если пользователь прямо попросил`,
    '   или ты работаешь в самой ветке Production; и тогда — только чтение.',
    ...(devDb === 'copy:production'
      ? ['   База Development-сборки — копия базы Production на момент сборки: «проверить на реальных данных» — это в ней.']
      : devDb.startsWith('copy:')
        ? [`   База Development-сборки — копия базы сборки ${code(devDb.slice(5))} на момент сборки.`]
        : []),
    `4. Не подменяй сборку ветки другой: ни Production, ни сборкой соседней ветки, ни базой из ${code('odoo.conf')}${notBuilds.length ? ',' : '.'}`,
    ...(notBuilds.length ? [`   ни стендом пользователя (${notBuilds.join(', ')}).`] : []),
    '   Сборки ветки нет, она остановлена или упала — скажи пользователю: Rebuild или Start ветки в приложении.',
    '',
    '## Как устроено',
    '',
    '| Что | Значение |',
    '|-----|----------|',
    `| Контейнер сборки | compose-проект ${code(cfg.naming.composeProject)}, контейнер ${code('<проект>-odoo-1')}; искать по labels (ниже) |`,
    `| Slug ветки | шаблон ${code(cfg.naming.slug)}${cfg.naming.slugStrip ? `, без ${code(cfg.naming.slugStrip)}` : ''}, символы кроме ${code('a-z0-9')} → ${code('-')}; Production — ${code(cfg.production.slug)}; точно — label ${code('bm.slug')} |`,
    `| URL | ${code(urlTpl)}${prodHost ? ` (Production: ${code(buildUrl(prodHost, i.proxyPort))})` : ''}; label ${code('bm.url')} |`,
    `| База | ${code(cfg.naming.db)}${prodDb ? ` (например ${code(prodDb)})` : ''}; точное имя — label ${code('bm.db')} |`,
    `| Postgres | ${pgRow} |`,
    `| Код в контейнере | ${code(cfg.runtime.repoMount)} |`,
    `| Код сборки на хосте | ${code(worktrees)} — служебные копии приложения: не править, не искать в них код |`,
    ...(local ? [`| Папка пользователя | ${code(local)} — код правим здесь |`] : []),
    ...(cfg.repo.moduleRoots.length ? [`| Папки модулей | ${list(cfg.repo.moduleRoots)} |`] : []),
    ...(hasDebug ? [`| debugpy | у каждой сборки свой порт на ${code('127.0.0.1')}: ${code(`docker port $C ${dbgPort}`)} |`] : []),
    `| Логи приложения | ${code(i.logsDir)}: ${code('core.log')}, ${code('jobs/<id>-<тип>.log')}, ${code(`builds/${id}/<slug>-<n>.log`)} и ${code('.tests.log')} |`,
    '',
    '## Какие сборки можно менять',
    '',
    `- Production ${code(cfg.production.branch)}${protectedOthers.length ? ` и защищённые ветки (${list(protectedOthers)})` : ''} — **только чтение**: логи,`,
    `  ${code('SELECT')}. У их контейнеров label ${code('bm.stage=production')} или ${code('bm.protected=true')}; защиту ветки пользователь`,
    '  может включить и позже — перед любой записью проверь label.',
    `- Остальные ветки — Development: можно ${code('-u')} / ${code('-i')}, тесты, ${code('docker restart')}.`,
    '',
    '## Как код попадает в сборку',
    '',
    `- Обычный путь: правка${local ? ` в ${code(local)}` : ''} → commit → push ветки. Приложение делает fetch ${fetchText},`,
    '  обновляет изменённые модули и запускает их тесты (по настройкам стадии). Commit и push — только по просьбе пользователя.',
    '- Быстрый путь (включает пользователь): вкладка ветки Editor → «Из моей папки». Сборка монтирует папку как есть:',
    `  Restart показывает правки Python без коммита, для XML и данных нужен ${code('-u')}. Коммит кода, на котором в сборке`,
    `  уже сделаны ${code('-u')} изменённых модулей и их тесты, сборку не повторяет: приложение только отмечает её коммитом.`,
    '  Пока в этой папке открыта другая ветка, сборка заблокирована: приложение и bm отказывают (кроме Stop). Не',
    '  переключай ветку в папке пользователя, чтобы «починить» сборку, — это решает пользователь.',
    '',
    ...(i.cli
      ? [
          '## Команды приложения: bm (основной способ)',
          '',
          'Работают, пока приложение запущено. Каждая команда — задача в очереди приложения: её видно в приложении',
          '(History, Audit Logs), итог тестов попадает в бейдж Test сборки. Production и защищённые ветки bm не меняет.',
          '',
          '```bash',
          `BM="${i.cli.sh}"   # ${i.windows ? 'Git Bash' : 'zsh / bash'}`,
          '"$BM" status                        # ветки, сборки, URL, базы, итог тестов; --json — для разбора',
          '"$BM" modules <ветка> -u <модуль>   # -i <модуль> — установить; контейнер на время останавливается',
          '"$BM" test <ветка> <модуль>         # тесты на временной копии базы сборки',
          '"$BM" restart <ветка>',
          '```',
          '',
          ...(i.cli.cmd ? [`PowerShell / cmd: ${code(`& "${i.cli.cmd}" status`)} и так далее.`, ''] : []),
          `- Ветка — имя или slug. Проект — по текущей папке, иначе ${code(`-p ${id}`)}.`,
          '- Код выхода: 0 — готово; 1 — ошибка или упавшие тесты (текст в stderr); 2 — приложение не запущено: попроси',
          '  пользователя запустить его или используй docker-команды ниже.',
          `- Справка — ${code('"$BM" help')}.`,
          '',
          '## Без приложения: docker (запасной путь)',
          '',
          `Если ${code('bm')} вернул код 2 (приложение не запущено). Прогоны отсюда не попадают в History и бейдж Test.`,
          '',
        ]
      : []),
    '## Найти сборку',
    '',
    '```bash',
    `docker ps -a ${filter} \\`,
    `  --format '{{.Names}}\\t{{.Label "bm.branch.name"}}\\t{{.Label "bm.stage"}}\\t{{.Label "bm.protected"}}\\t{{.Label "bm.db"}}\\t{{.Label "bm.url"}}\\t{{.Status}}'`,
    '',
    `C=$(docker ps -q ${filter} --filter label=bm.branch.name=<ветка>)`,
    `DB=$(docker inspect -f '{{index .Config.Labels "bm.db"}}' $C)`,
    '```',
    '',
    'Сборки нет или она остановлена — попроси пользователя запустить (Start) или собрать (Rebuild) её в приложении.',
    '',
    '## Обновить модуль (только Development)',
    '',
    'Пользователю советуй приложение: вкладка ветки Tools → «Модули вручную» — задача в очереди приложения,',
    `база и опции подставляются сами.${i.cli ? ` Ассистенту — ${code('bm modules')}, а команды ниже — только без приложения.` : ''}`,
    '',
    `Ассистент — командой. Опции Odoo сборки (конфиг, ${code('--data-dir')}${usesAddonsPath ? `, ${code('--addons-path')} из кода ветки` : ''}) лежат`,
    `в label ${code('bm.odoo.args')}; ${code('-d')} — только из ${code('bm.db')}, не из ${code('odoo.conf')}.`,
    '',
    '```bash',
    `docker inspect -f '{{index .Config.Labels "bm.stage"}} protected={{index .Config.Labels "bm.protected"}}' $C  # production или protected=true — стоп`,
    `ARGS=$(docker inspect -f '{{index .Config.Labels "bm.odoo.args"}}' $C)`,
    `bmodoo() { ${i.windows ? 'MSYS_NO_PATHCONV=1 ' : ''}docker exec -i "$C" sh -c 'PGPASSWORD=$PASSWORD; export PGPASSWORD; exec odoo "$@"' odoo "$@" $ARGS -d "$DB"; }`,
    'bmodoo -u <модуль> --stop-after-init --no-http',
    'docker restart $C',
    '```',
    '',
    ...(i.windows
      ? [
          'PowerShell:',
          '',
          '```powershell',
          `$C = docker ps -q ${filter} --filter label=bm.branch.name=<ветка>`,
          `$L = (docker inspect $C | ConvertFrom-Json)[0].Config.Labels`,
          `"$($L.'bm.stage') protected=$($L.'bm.protected')"  # production или protected=true — стоп`,
          `$DB = $L.'bm.db'`,
          `$OdooArgs = $L.'bm.odoo.args' -split ' '`,
          `function bmodoo { docker exec -i $C sh -c 'PGPASSWORD=$PASSWORD; export PGPASSWORD; exec odoo $@' odoo @args @OdooArgs -d $DB }`,
          'bmodoo -u <модуль> --stop-after-init --no-http',
          'docker restart $C',
          '```',
          '',
        ]
      : []),
    `- ${code('bmodoo')} запускает Odoo внутри контейнера сборки с её опциями. Пароль БД берётся из переменной контейнера`,
    `  ${code('PASSWORD')} (${code('docker exec')} обходит entrypoint образа, который обычно его передаёт) и не проходит через твою команду.`,
    `- Новый модуль — ${code('-i')} вместо ${code('-u')}.`,
    ...(i.windows
      ? [
          `- ${code('MSYS_NO_PATHCONV=1')} нужен в Git Bash: иначе пути ${code('/etc/…')} в опциях превратятся в пути Windows.`,
          `- В PowerShell labels читай через ${code('ConvertFrom-Json')}, как выше: Windows PowerShell 5.1 выкидывает двойные кавычки`,
          `  из аргументов ${code(`docker inspect -f '{{index .Config.Labels "…"}}'`)}.`,
        ]
      : []),
    `- Label ${code('bm.odoo.args')} пуст — сборка создана старой версией приложения. Попроси пользователя нажать`,
    `  «Применить» на странице ветки (плашка «конфигурация изменилась»: контейнер пересоздаётся, база остаётся); до этого задай ${code(`ARGS='${staticArgs}'`)}${usesAddonsPath ? ` и добавь к нему ${code('--addons-path=…')} из ${code(`docker inspect -f '{{json .Config.Cmd}}' $C`)}` : ''}.`,
    ...(usesAddonsPath
      ? [
          `- Ветка «Из моей папки» получила новую папку модулей (новый корень с ${code('__manifest__.py')}) — в ${code('bm.odoo.args')} и у сервера`,
          `  сборки её ещё нет. Ставь такие модули через ${i.cli ? code('bm modules') : '«Модули вручную» в приложении'}: сервер пересоздаётся с новым ${code('--addons-path')}.`,
          `  Иначе попроси пользователя нажать «Применить» (плашка на странице ветки); ${code('docker restart')} этого не сделает.`,
        ]
      : []),
    '',
    '## Тесты',
    '',
    ...(i.cli
      ? [`Основной способ — ${code('bm test <ветка> <модуль>')}: итог попадает в History и бейдж Test. Без приложения:`, '']
      : []),
    `${code('$C')}, ${code('$DB')}, ${code('bmodoo')} — как выше; тесты тоже только в Development-сборке.`,
    '',
    '```bash',
    `bmodoo -u <модуль> --stop-after-init --http-port=8070 --test-enable --test-tags ${tags}`,
    '```',
    '',
    `- ${code('--http-port=8070')}: порт 8069 занят сервером сборки, без этого ${code('HttpCase')} не поднимет свой сервер.`,
    '- Тесты пишут в базу этой сборки; для чистого прогона — Rebuild в приложении.',
    '- Прогон через docker не попадает в History и бейдж Test приложения. Автотесты самого приложения (изменённые модули при',
    `  каждой сборке): вкладка Logs → ${code('tests.log')}, файлы ${code(`${i.logsDir}/builds/${id}/<slug>-<n>.tests.log`)}.`,
    '',
    '## Логи, база, odoo shell',
    '',
    '```bash',
    'docker logs -f --tail 200 $C',
    `echo "print(env['res.users'].search_count([]))" | bmodoo shell --no-http`,
    '```',
    '',
    ...psql,
    '',
    `В защищённых сборках — только чтение: ${code('SELECT')}, в ${code('odoo shell')} без ${code('env.cr.commit()')}.`,
    '',
    ...(hasDebug
      ? [
          '## Отладка (debugpy)',
          '',
          `Порт — ${code(`docker port $C ${dbgPort}`)}. Конфигурацию для VS Code / Cursor пишет приложение: вкладка ветки`,
          `Tools → Debug → «Добавить в .vscode/launch.json папки кода». Точки останова ставь в файлах ${code(worktrees)}`,
          `(при «Из моей папки» — в папке пользователя).`,
          '',
        ]
      : []),
    '## Только через приложение',
    '',
    'Ассистент этого **не делает** — только пользователь кнопками приложения (Rebuild, Drop, Start/Stop, Backups, Settings):',
    '',
    `- ${code('docker compose down/rm')}, ${code('docker rm')}, ${code('docker stop')} контейнеров ${code('bm-*')}; ничего не делать с ${code('bm-traefik')}${managed ? ` и ${code(pgName)} (кроме psql)` : ''};`,
    `- ${code('dropdb')}, ${code('DROP DATABASE')}, создание и копирование баз сборок;`,
    `- удаление и правка ${code(`${cfg.repo.worktreesDir}/${id}`)}, filestore сборок в ${code(cfg.runtime.filestore.hostDir)}${cfg.repo.mirrorDir ? `, копии репозитория ${code(cfg.repo.mirrorDir)}` : ''};`,
    `- любые записи в Production и защищённые сборки (${code('-u')}, ${code('-i')}, restart, ${code('UPDATE')} / ${code('INSERT')} / ${code('DELETE')});`,
    `- настройки ${code(`${i.configDir}/projects/${id}.yaml`)} и ${code('app.yaml')} — только по просьбе пользователя; пароль Postgres`,
    '  из них не читать и не выводить;',
    ...(protectedContainers.length || pg.protectedDbs.length
      ? [`- ${[...protectedContainers.map((c) => `контейнер ${code(c)}`), ...pg.protectedDbs.map((d) => `база ${code(d)}`)].join(', ')} — только по явной просьбе;`]
      : []),
    '- удаление ветки на GitHub — только пользователь: если у ветки включено «Удалять, если ветку удалили на GitHub», после',
    '  fetch приложение удалит её сборку, базу, filestore и worktree. Данные нужны — сначала снапшот во вкладке Backups.',
    '',
    '## Если приложение ошиблось',
    '',
    'Ошибка приложения, непонятное сообщение, пришлось руками сделать то, что должно делать приложение, — скажи',
    `пользователю. Issue в ${code(i.appRepository)} (${code(`https://github.com/${i.appRepository}/issues`)}) — только по его решению.`,
    '',
  ];
  return lines.join('\n');
}

/** Skill text with the marker line: version of the app and hash of the text, to tell hand edits from old versions. */
export function skillFile(i: SkillInput): string {
  const body = renderSkill(i);
  return `${body}<!-- generated by Odoo Branch Manager ${i.appVersion}; sha256:${skillHash(body)} -->\n`;
}
